### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Frogperson** [maxanier/GodlyVampirism#1]
It looks like this mod is currently incompatible with servers and gives an internal server error when you try to connect

```
java.lang.RuntimeException: Attempted to load class net/minecraft/server/integrated/IntegratedServer for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[custompack.jar:35.1]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at de.teamlapen.godlyvampirism.GodlyVampirismMod.lambda$onCommandsRegister$1(GodlyVampirismMod.java:78) ~[godly-vampirism:?]
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:66) ~[?:?]
	at net.minecraft.command.Commands.func_197052_a(Commands.java:279) ~[?:?]
	at net.minecraft.command.Commands.func_197052_a(Commands.java:305) ~[?:?]
	at net.minecraft.command.Commands.func_197051_a(Commands.java:273) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_187245_a(PlayerList.java:597) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_187243_f(PlayerList.java:491) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:162) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
	```

**Comment by maxanier** [comment]
Thx for reporting. Fixed in 1.0.1
